my:
  greeting: Hello Werld
  list.properties: One,Two,Three
db:
  connection: facebook.com
  port: 8086
  host: host

#expose everything(http://localhost:8080/actuator/configprops)
management.endpoints.web.exposure:
  include: "*"
