my:
  greeting: Hello Werld
  list.properties: One,Two,Three
db:
  connection: "application-test.yml profile"
  port: 8087
  host: host

#expose everything(http://localhost:8080/actuator/configprops)
management.endpoints.web.exposure:
  include: "*"
